### ISSUE TITLE
config files for DL3DV

### ISSUE THREAD

**Issue by ishaybee** [arthurhero/Long-LRM#2]
Hi,
thanks for your great work.
can you provide example config file for DL3DV?

**Comment by Vincento-Wang** [comment]
![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)

I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.

checkpoint_dir: ./checkpoints/20250116
use_tf32: False
use_amp: True
amp_dtype: fp16 #bf16

evaluation: False
evaluation_dir: null

training:
  batch_size_per_gpu: 1
  num_workers: 16
  prefetch_factor: 2
  train_steps: 60000
  grad_accum_steps: 1
  resume_ckpt: null

  weight_decay: 0.05
  lr: 0.00004
  warmup_steps: 2000
  scheduler_type: "cosine"
  beta1: 0.9
  beta2: 0.999
  grad_clip_norm: 5.0
  allowed_gradnorm_factor: 5.0

  print_every: 1000
  wandb_every: 1000
  vis_every: 1000
  checkpoint_every: 10000
  save_gaussian_every: 10000
  save_video_every: 10000

  api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87"
  wandb_entity: anonymous
  wandb_project: llrm
  wandb_offline: True

  l2_loss: 1.0
  perceptual_loss: 0.5
  opacity_loss: 0.1
  depth_loss: 0.01
  
data:
    data_path: "data/example_data/mydesk.txt"
    resize_h: 256
    resize_w: -1
    resize_short: 256
    patch_size: 8
    square_crop: True
    
    input_frame_select_type: "random"
    target_frame_select_type: "random"
    shuffle_input_prob: 0.5
    reverse_input_prob: 0.5
    num_input_frames: 32
    num_target_frames: 8

    target_has_input: True
    min_frame_dist: 64
    max_frame_dist: 128

    scene_scale: 1.0
    
model: 
    dim: [256]
    patch_size: 8
    num_layers: 8
    block_type: "mtmtmtmt"
    merge_layers: []

    transformer: 
        head_dim: 64

    mamba2:
        d_state: 256

    num_global_tokens: 2

    gaussians:
        sh_degree: 2
        max_dist: 1
        scale_bias: 0
        scale_max: 10
        opacity_bias: 0
        near_plane: 0.1
        far_plane: 100
        prune_ratio: 0.1
        random_ratio: 0.2

**Comment by ishaybee** [comment]
Thanks!
Maybe @arthurhero  can help with this issue.

**Comment by xiac00** [comment]
> ![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)
> 
> I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.
> 
> checkpoint_dir: ./checkpoints/20250116 use_tf32: False use_amp: True amp_dtype: fp16 #bf16
> 
> evaluation: False evaluation_dir: null
> 
> training: batch_size_per_gpu: 1 num_workers: 16 prefetch_factor: 2 train_steps: 60000 grad_accum_steps: 1 resume_ckpt: null
> 
> weight_decay: 0.05 lr: 0.00004 warmup_steps: 2000 scheduler_type: "cosine" beta1: 0.9 beta2: 0.999 grad_clip_norm: 5.0 allowed_gradnorm_factor: 5.0
> 
> print_every: 1000 wandb_every: 1000 vis_every: 1000 checkpoint_every: 10000 save_gaussian_every: 10000 save_video_every: 10000
> 
> api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87" wandb_entity: anonymous wandb_project: llrm wandb_offline: True
> 
> l2_loss: 1.0 perceptual_loss: 0.5 opacity_loss: 0.1 depth_loss: 0.01
> 
> data: data_path: "data/example_data/mydesk.txt" resize_h: 256 resize_w: -1 resize_short: 256 patch_size: 8 square_crop: True
> 
> ```
> input_frame_select_type: "random"
> target_frame_select_type: "random"
> shuffle_input_prob: 0.5
> reverse_input_prob: 0.5
> num_input_frames: 32
> num_target_frames: 8
> 
> target_has_input: True
> min_frame_dist: 64
> max_frame_dist: 128
> 
> scene_scale: 1.0
> ```
> 
> model: dim: [256] patch_size: 8 num_layers: 8 block_type: "mtmtmtmt" merge_layers: []
> 
> ```
> transformer: 
>     head_dim: 64
> 
> mamba2:
>     d_state: 256
> 
> num_global_tokens: 2
> 
> gaussians:
>     sh_degree: 2
>     max_dist: 1
>     scale_bias: 0
>     scale_max: 10
>     opacity_bias: 0
>     near_plane: 0.1
>     far_plane: 100
>     prune_ratio: 0.1
>     random_ratio: 0.2
> ```

Thanks for your config. I follow the config and train the model but get rendered images with just pure color. I wonder whether you meet the same problem and any advice?

**Comment by lhmd** [comment]
> ![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)
> 
> I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.
> 
> checkpoint_dir: ./checkpoints/20250116 use_tf32: False use_amp: True amp_dtype: fp16 #bf16
> 
> evaluation: False evaluation_dir: null
> 
> training: batch_size_per_gpu: 1 num_workers: 16 prefetch_factor: 2 train_steps: 60000 grad_accum_steps: 1 resume_ckpt: null
> 
> weight_decay: 0.05 lr: 0.00004 warmup_steps: 2000 scheduler_type: "cosine" beta1: 0.9 beta2: 0.999 grad_clip_norm: 5.0 allowed_gradnorm_factor: 5.0
> 
> print_every: 1000 wandb_every: 1000 vis_every: 1000 checkpoint_every: 10000 save_gaussian_every: 10000 save_video_every: 10000
> 
> api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87" wandb_entity: anonymous wandb_project: llrm wandb_offline: True
> 
> l2_loss: 1.0 perceptual_loss: 0.5 opacity_loss: 0.1 depth_loss: 0.01
> 
> data: data_path: "data/example_data/mydesk.txt" resize_h: 256 resize_w: -1 resize_short: 256 patch_size: 8 square_crop: True
> 
> ```
> input_frame_select_type: "random"
> target_frame_select_type: "random"
> shuffle_input_prob: 0.5
> reverse_input_prob: 0.5
> num_input_frames: 32
> num_target_frames: 8
> 
> target_has_input: True
> min_frame_dist: 64
> max_frame_dist: 128
> 
> scene_scale: 1.0
> ```
> 
> model: dim: [256] patch_size: 8 num_layers: 8 block_type: "mtmtmtmt" merge_layers: []
> 
> ```
> transformer: 
>     head_dim: 64
> 
> mamba2:
>     d_state: 256
> 
> num_global_tokens: 2
> 
> gaussians:
>     sh_degree: 2
>     max_dist: 1
>     scale_bias: 0
>     scale_max: 10
>     opacity_bias: 0
>     near_plane: 0.1
>     far_plane: 100
>     prune_ratio: 0.1
>     random_ratio: 0.2
> ```

Thank you for your contribution! I found this yaml file didn't include all cfg(such as cfg.training.perceptual_out_idx),  could you please show a full version of the config file? Thank you very much!

**Comment by Vincento-Wang** [comment]
> > ![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)
> > I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.
> > checkpoint_dir: ./checkpoints/20250116 use_tf32: False use_amp: True amp_dtype: fp16 #bf16
> > evaluation: False evaluation_dir: null
> > training: batch_size_per_gpu: 1 num_workers: 16 prefetch_factor: 2 train_steps: 60000 grad_accum_steps: 1 resume_ckpt: null
> > weight_decay: 0.05 lr: 0.00004 warmup_steps: 2000 scheduler_type: "cosine" beta1: 0.9 beta2: 0.999 grad_clip_norm: 5.0 allowed_gradnorm_factor: 5.0
> > print_every: 1000 wandb_every: 1000 vis_every: 1000 checkpoint_every: 10000 save_gaussian_every: 10000 save_video_every: 10000
> > api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87" wandb_entity: anonymous wandb_project: llrm wandb_offline: True
> > l2_loss: 1.0 perceptual_loss: 0.5 opacity_loss: 0.1 depth_loss: 0.01
> > data: data_path: "data/example_data/mydesk.txt" resize_h: 256 resize_w: -1 resize_short: 256 patch_size: 8 square_crop: True
> > ```
> > input_frame_select_type: "random"
> > target_frame_select_type: "random"
> > shuffle_input_prob: 0.5
> > reverse_input_prob: 0.5
> > num_input_frames: 32
> > num_target_frames: 8
> > 
> > target_has_input: True
> > min_frame_dist: 64
> > max_frame_dist: 128
> > 
> > scene_scale: 1.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > model: dim: [256] patch_size: 8 num_layers: 8 block_type: "mtmtmtmt" merge_layers: []
> > ```
> > transformer: 
> >     head_dim: 64
> > 
> > mamba2:
> >     d_state: 256
> > 
> > num_global_tokens: 2
> > 
> > gaussians:
> >     sh_degree: 2
> >     max_dist: 1
> >     scale_bias: 0
> >     scale_max: 10
> >     opacity_bias: 0
> >     near_plane: 0.1
> >     far_plane: 100
> >     prune_ratio: 0.1
> >     random_ratio: 0.2
> > ```
> 
> Thanks for your config. I follow the config and train the model but get rendered images with just pure color. I wonder whether you meet the same problem and any advice?

gaussian depth is difficult to estimate cause the problem.
 xyz, feature, scale, rotation, opacity = torch.split(gaussians, [3, (self.config.model.gaussians.sh_degree + 1) ** 2 * 3, 3, 4, 1], dim=-1)
check this line of code value range may help

**Comment by Vincento-Wang** [comment]
> > ![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)
> > I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.
> > checkpoint_dir: ./checkpoints/20250116 use_tf32: False use_amp: True amp_dtype: fp16 #bf16
> > evaluation: False evaluation_dir: null
> > training: batch_size_per_gpu: 1 num_workers: 16 prefetch_factor: 2 train_steps: 60000 grad_accum_steps: 1 resume_ckpt: null
> > weight_decay: 0.05 lr: 0.00004 warmup_steps: 2000 scheduler_type: "cosine" beta1: 0.9 beta2: 0.999 grad_clip_norm: 5.0 allowed_gradnorm_factor: 5.0
> > print_every: 1000 wandb_every: 1000 vis_every: 1000 checkpoint_every: 10000 save_gaussian_every: 10000 save_video_every: 10000
> > api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87" wandb_entity: anonymous wandb_project: llrm wandb_offline: True
> > l2_loss: 1.0 perceptual_loss: 0.5 opacity_loss: 0.1 depth_loss: 0.01
> > data: data_path: "data/example_data/mydesk.txt" resize_h: 256 resize_w: -1 resize_short: 256 patch_size: 8 square_crop: True
> > ```
> > input_frame_select_type: "random"
> > target_frame_select_type: "random"
> > shuffle_input_prob: 0.5
> > reverse_input_prob: 0.5
> > num_input_frames: 32
> > num_target_frames: 8
> > 
> > target_has_input: True
> > min_frame_dist: 64
> > max_frame_dist: 128
> > 
> > scene_scale: 1.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > model: dim: [256] patch_size: 8 num_layers: 8 block_type: "mtmtmtmt" merge_layers: []
> > ```
> > transformer: 
> >     head_dim: 64
> > 
> > mamba2:
> >     d_state: 256
> > 
> > num_global_tokens: 2
> > 
> > gaussians:
> >     sh_degree: 2
> >     max_dist: 1
> >     scale_bias: 0
> >     scale_max: 10
> >     opacity_bias: 0
> >     near_plane: 0.1
> >     far_plane: 100
> >     prune_ratio: 0.1
> >     random_ratio: 0.2
> > ```
> 
> Thank you for your contribution! I found this yaml file didn't include all cfg(such as cfg.training.perceptual_out_idx), could you please show a full version of the config file? Thank you very much!

I just change the code. this may have no big influence on the result.

        self.blocks = nn.ModuleList()
        out_idx = [1] #config.training.perceptual_out_idx
        out_idx = [0] + out_idx
        self.layer_weights = [1] #config.training.perceptual_out_weights
        assert len(self.layer_weights) == len(out_idx) - 1

**Comment by Vincento-Wang** [comment]
config file according to the paper, I use the demo dataset for training test, suffer from gradient explosion, I have not train on the full dataset.

checkpoint_dir: ./checkpoints/20250116
use_tf32: False
use_amp: True
amp_dtype: fp16 #bf16

evaluation: False
evaluation_dir: null

training:
  batch_size_per_gpu: 1
  num_workers: 16
  prefetch_factor: 2
  train_steps: 60000
  grad_accum_steps: 1
  resume_ckpt: null

  weight_decay: 0.05
  lr: 0.00004
  warmup_steps: 2000
  scheduler_type: "cosine"
  beta1: 0.9
  beta2: 0.999
  grad_clip_norm: 5.0
  allowed_gradnorm_factor: 5.0

  print_every: 1000
  wandb_every: 1000
  vis_every: 1000
  checkpoint_every: 10000
  save_gaussian_every: 10000
  save_video_every: 10000

  api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87"
  wandb_entity: anonymous
  wandb_project: llrm
  wandb_offline: True

  l2_loss: 1.0
  perceptual_loss: 0.5
  opacity_loss: 0.1
  depth_loss: 0.01
  
data:
    data_path: "data/example_data/mydesk.txt"
    resize_h: 256
    resize_w: -1
    resize_short: 256
    patch_size: 8
    square_crop: True
    
    input_frame_select_type: "random"
    target_frame_select_type: "random"
    shuffle_input_prob: 0.5
    reverse_input_prob: 0.5
    num_input_frames: 32
    num_target_frames: 8

    target_has_input: True
    min_frame_dist: 64
    max_frame_dist: 128

    scene_scale: 1.0
    
model: 
    dim: [256]
    patch_size: 8
    num_layers: 24
    block_type: "mmmmmmmtmmmmmmmtmmmmmmmt"
    merge_layers: [8,16]

    transformer: 
        head_dim: 64

    mamba2:
        d_state: 256

    num_global_tokens: 2

    gaussians:
        sh_degree: 2
        max_dist: 1
        scale_bias: 0
        scale_max: 10
        opacity_bias: 0
        near_plane: 0.1
        far_plane: 100
        prune_ratio: 0.1
        random_ratio: 0.2

**Comment by lhmd** [comment]
> > > ![Image](https://github.com/user-attachments/assets/623240e6-14f7-40a1-8dc4-748229dd0350)
> > > I implement one config file according to the paper detailed, but suffers Gradient Explosion， may help you.
> > > checkpoint_dir: ./checkpoints/20250116 use_tf32: False use_amp: True amp_dtype: fp16 #bf16
> > > evaluation: False evaluation_dir: null
> > > training: batch_size_per_gpu: 1 num_workers: 16 prefetch_factor: 2 train_steps: 60000 grad_accum_steps: 1 resume_ckpt: null
> > > weight_decay: 0.05 lr: 0.00004 warmup_steps: 2000 scheduler_type: "cosine" beta1: 0.9 beta2: 0.999 grad_clip_norm: 5.0 allowed_gradnorm_factor: 5.0
> > > print_every: 1000 wandb_every: 1000 vis_every: 1000 checkpoint_every: 10000 save_gaussian_every: 10000 save_video_every: 10000
> > > api_key_path: "b7d9b515e39b01b0b5e8bbfa867273a9781d4f87" wandb_entity: anonymous wandb_project: llrm wandb_offline: True
> > > l2_loss: 1.0 perceptual_loss: 0.5 opacity_loss: 0.1 depth_loss: 0.01
> > > data: data_path: "data/example_data/mydesk.txt" resize_h: 256 resize_w: -1 resize_short: 256 patch_size: 8 square_crop: True
> > > ```
> > > input_frame_select_type: "random"
> > > target_frame_select_type: "random"
> > > shuffle_input_prob: 0.5
> > > reverse_input_prob: 0.5
> > > num_input_frames: 32
> > > num_target_frames: 8
> > > 
> > > target_has_input: True
> > > min_frame_dist: 64
> > > max_frame_dist: 128
> > > 
> > > scene_scale: 1.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > model: dim: [256] patch_size: 8 num_layers: 8 block_type: "mtmtmtmt" merge_layers: []
> > > ```
> > > transformer: 
> > >     head_dim: 64
> > > 
> > > mamba2:
> > >     d_state: 256
> > > 
> > > num_global_tokens: 2
> > > 
> > > gaussians:
> > >     sh_degree: 2
> > >     max_dist: 1
> > >     scale_bias: 0
> > >     scale_max: 10
> > >     opacity_bias: 0
> > >     near_plane: 0.1
> > >     far_plane: 100
> > >     prune_ratio: 0.1
> > >     random_ratio: 0.2
> > > ```
> > 
> > 
> > Thank you for your contribution! I found this yaml file didn't include all cfg(such as cfg.training.perceptual_out_idx), could you please show a full version of the config file? Thank you very much!
> 
> I just change the code. this may have no big influence on the result.
> 
> ```
>     self.blocks = nn.ModuleList()
>     out_idx = [1] #config.training.perceptual_out_idx
>     out_idx = [0] + out_idx
>     self.layer_weights = [1] #config.training.perceptual_out_weights
>     assert len(self.layer_weights) == len(out_idx) - 1
> ```

Thank you very much! But I have another question, how can I fit dl3dv dataset to the format that this repo use, is there any scripts?

**Comment by junyiouy** [comment]
FYI, I think this repo currently is not suitable for reproduction of this paper. I tried many modifications but always failed to let the models converge. Perhaps it would be better to wait for the authors to update these codes.

**Comment by Ryanrenqian** [comment]
I try following config, it seems to converge.  

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/d6deee28-921b-42e1-9a9f-cba7a654859c" />

```
config_name: long-lrm-dl3dv-uniform
checkpoint_dir: ./checkpoints/dl3dv/uniform
use_amp: True
use_tf32: True
amp_dtype: fp16
training:
  batch_size_per_gpu: 16  # dataloader
  num_workers: 16
  prefetch_factor: 4
  train_steps: 60000
  grad_accum_steps: 1
  
  weight_decay: 0.05 # optimizer
  lr: 0.0004
  beta1: 0.9
  beta2: 0.99
  
  warmup_steps: 2000 # scheduler
  scheduler_type: "cosine"
  resume_ckpt: null 

  perceptual_loss: 0.5 # loss
  perceptual_out_idx: []
  perceptual_out_weights: []
  perceptual_feature_scale: 1.0
  depth_loss: 0.01
  l2_loss: 1.0
  opacity_loss: 0.1
  grad_clip_norm: 1.0
  allowed_gradnorm_factor: 5.0

  print_every: 10 #log
  wandb_every: 5
  checkpoint_every: 100
  vis_every: 100
  save_video_every: 10000
  save_gaussian_every: 10000

  wandb_offline: false
  wandb_project: long-lrm-dl3dv
  wandb_entity: renqian1994
  api_key_path: "/jfs/qian.ren/Long-LRM/configs/wandb.yaml"
evaluation: false
evaluation_dir: './evaluation/dl3dv/uniform'

model:
  patch_size: 8
  num_layers: 24
  dim: [256,1024]
  block_type: 'mmmmmmmtmmmmmmmtmmmmmmmt'
  merge_layers: [8]
  num_global_tokens: 2
  transformer:
    head_dim: 64
  mamba2:
    d_state: 256
  gaussians:
    sh_degree: 2
    max_dist: 1
    scale_bias: 0
    scale_max: 10
    near_plane: 0.1
    far_plane: 100
    align_to_pixel: true
    opacity_bias: 0
    opacity_threshold: 0.001
    prune_ratio: 0.1
    random_ratio: 0.2
data:
  data_path: "data/dl3dv/dl3dv.txt"
  scene_scale: 1
  resize_h: 256
  resize_w: -1
  patch_size: 8
  square_crop: True
  num_input_frames: 32
  num_target_frames: 8
  input_frame_select_type: "uniform" #random,uniform,uniform_every,kmeans
  target_frame_select_type: "uniform" # random,uniform,uniform_every
  shuffle_input_prob: 0.5
  reverse_input_prob: 0.5
  target_uniform_every: 3
  target_has_input: True
  min_frame_dist: 64
  max_frame_dist: 128

```
